name = "Culture Of Code v2"
license = "MIT"
licenselink = "https://github.com/kpb/hugo-coc-v2/blob/main/LICENSE"
description = "Culture of Code theme version 2"
homepage = "https://cultureofcode.com"
tags = []
features = []

[author]
  name = "Kenneth Bowen"
  homepage = "https://cultureofcode.com"
